spring:
  application:
    name: guess-pokemon

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
            - db
